---
title: "Project: The Forecasting Tourism 2010 Competition"
subtitle: "EM1415"
author: "Marco Solari, 875475"
format: pdf
papersize: a4
geometry:
  - left=23mm
  - right=35.5mm
  - marginparwidth=23mm
  - top=30mm
  - bottom=30mm
toc: true
number-sections: true
highlight-style: gruvbox
code-block-bg: true

mainfont: 'Atkinson Hyperlegible'
monofont: 'Fira Code'
mathfont: 'Noto Sans Math'
sansfont: RobotoSerifNormalRoman-Medium
fontsize: 9pt        

fig-align: 'center'
fig-width: 10
fig-height: 8

include-in-header: 
  text: |
    \usepackage{fvextra}
    \usepackage{listings}
    \usepackage{lstfiracode}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    \newfontfamily\sectionfont[]{RobotoSerifNormalRoman-ExtraBold}
    \newfontfamily\subsectionfont[]{RobotoSerifNormalRoman-Medium}
    \newfontfamily\subsubsectionfont[]{RobotoSerifNormalRoman-Medium}
    \addtokomafont{section}{\sectionfont}
    \addtokomafont{subsection}{\subsectionfont}
    \addtokomafont{subsubsection}{\subsubsectionfont}
    \makeatletter
    \def\verbatim@nolig@list{}
    \makeatother

reference-location: margin 
citation-location: margin 
---

```{r setup}
knitr::opts_chunk$set(
  echo = T,
  dev = "cairo_pdf"
)

libraries_list <- c(
  "tidyverse",
  "fpp3"
)

lapply(
  libraries_list,
  require,
  character.only = TRUE
)

theme_set(
  ggthemes::theme_tufte(
    base_size = 16,
    base_family = "Atkinson Hyperlegible"
  )
)
```

# Loading Data

```{r load data}
data_main <- readr::read_csv(
  "Data/tourism_data.csv",
  show_col_types = F
)
```

```{r checkig dimensions and NA 1}
data_main %>% dim
```

```{r checkig dimensions and NA 2}
data_main %>% is.na() %>% sum
```

```{r creating tourism tsibble}
tourism_full <- data_main %>% 
  mutate(
    Year = 1965:2007
  ) %>% 
  as_tsibble(
    index = Year
  )
```

```{r checking tsibble interval}
tourism_full %>% interval
```

```{r melted tsibble}
tmelt <- reshape2::melt(tourism_full,id="Year")
```

```{r full viz train}
#| fig-width: 12
#| fig-height: 12
tmelt %>% 
  filter(
    Year < 2004
  ) %>% 
  ggplot(
    aes(
      x = Year,
      y = log(
        value
        ),
      colour = variable,
      group = variable
      )
    ) + 
  geom_line(
    alpha = .8
  ) + 
  scale_color_viridis_d(
    option = "rocket"
  ) +
  theme(
    legend.position = "none"
    )
```

```{r full viz test}
#| fig-width: 12
#| fig-height: 12
tmelt %>% 
  filter(
    Year >=2004
  ) %>% 
  ggplot(
    aes(
      x = Year,
      y = log(
        value
        ),
      colour = variable,
      group = variable
      )
    ) + 
  geom_line(
    alpha = .8
  ) + 
  scale_color_viridis_d(
    option = "rocket"
  ) +
  theme(
    legend.position = "none"
    )
```

